import type {
  RepairSpec,
  Shop,
  Call,
  Quote,
  EvidenceSpan,
  Negotiation,
  Campaign,
  Session,
  AuditEvent,
} from "./types";

export const DEMO_SESSION_ID = "sess_demo_camry";
export const DEMO_SPEC_ID = "spec_demo_v1";
export const DEMO_CAMPAIGN_ID = "camp_demo_1";

const now = new Date("2026-07-18T14:00:00Z").toISOString();

export const seedSession: Session = {
  id: DEMO_SESSION_ID,
  mode: "demo",
  status: "campaign_running",
  createdAt: now,
};

export const seedSpec: RepairSpec = {
  id: DEMO_SPEC_ID,
  sessionId: DEMO_SESSION_ID,
  version: 1,
  status: "draft",
  vehicle: {
    year: 2020,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    mileage: 62000,
    vinLast8: "12345678",
  },
  diagnosisSource: "Uploaded dealer estimate — sample_estimate.pdf",
  operations: [
    {
      id: "op_pads",
      description: "Replace front brake pads",
      partsPreference: "premium_aftermarket",
      customerSuppliedParts: false,
    },
    {
      id: "op_rotors",
      description: "Replace front brake rotors",
      partsPreference: "premium_aftermarket",
      customerSuppliedParts: false,
    },
  ],
  location: { city: "Charlotte", region: "NC", postal: "28202" },
  completionByDays: 7,
  requiredQuoteFields: [
    "parts",
    "labor",
    "diagnostic_fee",
    "shop_supply_fee",
    "tax",
    "all_in_total",
    "warranty",
    "earliest_appointment",
    "quote_expiration",
    "conditions",
  ],
  fieldMeta: {
    "vehicle.year": {
      source: "document",
      status: "verified",
      confidence: 0.99,
      excerpt: "2020 TOYOTA CAMRY SE",
    },
    "vehicle.make": {
      source: "document",
      status: "verified",
      confidence: 0.99,
      excerpt: "2020 TOYOTA CAMRY SE",
    },
    "vehicle.model": {
      source: "document",
      status: "verified",
      confidence: 0.99,
      excerpt: "2020 TOYOTA CAMRY SE",
    },
    "vehicle.trim": {
      source: "document",
      status: "verified",
      confidence: 0.94,
      excerpt: "TRIM: SE",
    },
    "vehicle.mileage": {
      source: "manual",
      status: "verified",
      confidence: 1,
      excerpt: "Confirmed by user: 62,000 miles",
    },
    "vehicle.vinLast8": {
      source: "document",
      status: "verified",
      confidence: 0.97,
      excerpt: "VIN ...12345678",
    },
    operations: {
      source: "document",
      status: "verified",
      confidence: 0.96,
      excerpt: "R&R FRONT BRAKE PADS AND ROTORS",
    },
    location: {
      source: "document",
      status: "verified",
      confidence: 0.9,
      excerpt: "CHARLOTTE, NC 28202",
    },
    completionByDays: { source: "manual", status: "missing", confidence: 0.0 },
  },
  createdAt: now,
};

export const seedShops: Shop[] = [
  {
    id: "shop_budget",
    name: "Budget Brake Center",
    phone: "+1 (704) 555-0142",
    phoneVerified: true,
    address: "2210 South Blvd, Charlotte, NC 28203",
    website: "budgetbrakeclt.example.com",
    hours: "Mon–Sat 7:30a–6:00p",
    discoverySource: "seed",
    demoPolicy: {
      label: "Low headline, hidden fees",
      behaviorNotes: [
        "Leads with a low headline price",
        "Does not volunteer shop or disposal fees",
        "Warranty is short unless asked",
      ],
    },
  },
  {
    id: "shop_precision",
    name: "Precision Auto Works",
    phone: "+1 (704) 555-0188",
    phoneVerified: true,
    address: "615 Providence Rd, Charlotte, NC 28207",
    website: "precisionautoclt.example.com",
    hours: "Mon–Fri 7:00a–6:00p",
    discoverySource: "seed",
    demoPolicy: {
      label: "Premium with real leverage response",
      behaviorNotes: [
        "Higher initial price with premium parts + long warranty",
        "Will reduce price or waive a fee once shown a verified competing quote",
      ],
    },
  },
  {
    id: "shop_queencity",
    name: "Queen City Garage",
    phone: "+1 (704) 555-0176",
    phoneVerified: true,
    address: "1104 Central Ave, Charlotte, NC 28204",
    website: "queencitygarage.example.com",
    hours: "Mon–Fri 8:00a–5:30p",
    discoverySource: "seed",
    demoPolicy: {
      label: "Gruff, evasive on itemization",
      behaviorNotes: [
        "Initially returns a range instead of a firm total",
        "Provides itemization after persistent questioning",
      ],
    },
  },
];

export const seedCampaign: Campaign = {
  id: DEMO_CAMPAIGN_ID,
  sessionId: DEMO_SESSION_ID,
  repairSpecId: DEMO_SPEC_ID,
  shopIds: seedShops.map((s) => s.id),
  status: "completed",
  startedAt: now,
  completedAt: now,
  mode: "replay",
};

// --- Transcripts (compact, evidence-carrying) ---
type Turn = Call["transcript"][number];
const budgetTranscript: Turn[] = [
  {
    index: 0,
    speaker: "agent",
    timeSeconds: 2,
    text: "Hi, calling on behalf of a customer with a 2020 Camry SE, 62,000 miles. Front pads and rotors, premium aftermarket. What's your out-the-door price?",
  },
  {
    index: 1,
    speaker: "shop",
    timeSeconds: 9,
    text: "Front pads and rotors on a Camry, we can do that for $489.",
  },
  {
    index: 2,
    speaker: "agent",
    timeSeconds: 18,
    text: "Great — is that all-in with tax, shop supplies, and disposal, or subtotal?",
  },
  {
    index: 3,
    speaker: "shop",
    timeSeconds: 24,
    text: "That's parts and labor. Shop fee's $45 on top, tax is separate, disposal is included.",
  },
  { index: 4, speaker: "agent", timeSeconds: 33, text: "Understood. Tax rate for 28202?" },
  {
    index: 5,
    speaker: "shop",
    timeSeconds: 37,
    text: "7.25%. So about $40 tax. Warranty is 90 days parts and labor.",
  },
  { index: 6, speaker: "agent", timeSeconds: 46, text: "Earliest appointment?" },
  { index: 7, speaker: "shop", timeSeconds: 49, text: "Thursday morning." },
  {
    index: 8,
    speaker: "agent",
    timeSeconds: 52,
    text: "Please confirm the final all-in total including every fee and tax.",
  },
  {
    index: 9,
    speaker: "shop",
    timeSeconds: 55,
    text: "The final all-in total is $574.",
  },
];
const precisionTranscript: Turn[] = [
  {
    index: 0,
    speaker: "agent",
    timeSeconds: 2,
    text: "Front pads and rotors, 2020 Camry SE, 62,000 miles, premium aftermarket. Full itemized quote please.",
  },
  {
    index: 1,
    speaker: "shop",
    timeSeconds: 10,
    text: "Parts $312, labor $228, shop supplies $28, tax $48.69. All-in $616.69. Warranty 12 months or 12,000 miles.",
  },
  { index: 2, speaker: "agent", timeSeconds: 22, text: "Diagnostic fee?" },
  { index: 3, speaker: "shop", timeSeconds: 25, text: "Waived — repair is already diagnosed." },
  { index: 4, speaker: "agent", timeSeconds: 30, text: "Earliest appointment and quote validity?" },
  { index: 5, speaker: "shop", timeSeconds: 34, text: "Two days out. Quote holds for 14 days." },
];
const queenTranscript: Turn[] = [
  {
    index: 0,
    speaker: "agent",
    timeSeconds: 2,
    text: "Looking for a firm quote — front pads and rotors, 2020 Camry SE.",
  },
  {
    index: 1,
    speaker: "shop",
    timeSeconds: 8,
    text: "Somewhere between six-twenty and seven-twenty depending on the rotors.",
  },
  {
    index: 2,
    speaker: "agent",
    timeSeconds: 14,
    text: "Premium aftermarket, same as the estimate. Can you give an itemized total?",
  },
  {
    index: 3,
    speaker: "shop",
    timeSeconds: 20,
    text: "Parts $305, labor $260, shop fee $35, disposal $5, tax $40. Six-forty-five. Warranty six months. Visual inspection required before we commit.",
  },
];

export const seedCalls: Call[] = [
  {
    id: "call_budget",
    campaignId: DEMO_CAMPAIGN_ID,
    shopId: "shop_budget",
    kind: "quote",
    status: "completed",
    phase: "quote_collected",
    currentObjective: "Confirm hidden fees",
    durationSeconds: 58,
    transcript: budgetTranscript,
    audioAvailable: true,
    audioUrl: "demo://audio/budget",
    createdAt: now,
  },
  {
    id: "call_precision",
    campaignId: DEMO_CAMPAIGN_ID,
    shopId: "shop_precision",
    kind: "quote",
    status: "completed",
    phase: "quote_collected",
    currentObjective: "Complete itemization",
    durationSeconds: 42,
    transcript: precisionTranscript,
    audioAvailable: true,
    audioUrl: "demo://audio/precision",
    createdAt: now,
  },
  {
    id: "call_queen",
    campaignId: DEMO_CAMPAIGN_ID,
    shopId: "shop_queencity",
    kind: "quote",
    status: "completed",
    phase: "quote_collected",
    currentObjective: "Force itemization from range",
    durationSeconds: 33,
    transcript: queenTranscript,
    audioAvailable: true,
    audioUrl: "demo://audio/queen",
    createdAt: now,
  },
];

export const seedQuotes: Quote[] = [
  {
    id: "q_budget",
    callId: "call_budget",
    shopId: "shop_budget",
    status: "complete",
    items: [
      {
        id: "qi_b1",
        category: "parts",
        description: "Premium aftermarket pads + rotors, front",
        amount: 285,
        included: true,
        partsGrade: "premium_aftermarket",
      },
      {
        id: "qi_b2",
        category: "labor",
        description: "Front brake service labor",
        amount: 204,
        included: true,
      },
      {
        id: "qi_b3",
        category: "shop_supply",
        description: "Shop supply fee",
        amount: 45,
        included: true,
        disclosureNote: "Disclosed only after direct question",
      },
      {
        id: "qi_b4",
        category: "tax",
        description: "Sales tax (7.25%)",
        amount: 40,
        included: true,
      },
    ],
    subtotal: 534,
    tax: 40,
    total: 574,
    currency: "USD",
    warrantyText: "90 days parts and labor",
    warrantyDays: 90,
    earliestDate: "2026-07-23",
    validUntil: "2026-07-25",
    completeness: 0.95,
    conditions: [],
    confirmedInCall: true,
    warnings: ["hidden_fee_disclosed_late"],
    createdAt: now,
  },
  {
    id: "q_precision",
    callId: "call_precision",
    shopId: "shop_precision",
    status: "complete",
    items: [
      {
        id: "qi_p1",
        category: "parts",
        description: "Premium aftermarket pads + rotors, front",
        amount: 312,
        included: true,
        partsGrade: "premium_aftermarket",
      },
      {
        id: "qi_p2",
        category: "labor",
        description: "Front brake service labor",
        amount: 228,
        included: true,
      },
      {
        id: "qi_p3",
        category: "shop_supply",
        description: "Shop supplies",
        amount: 28,
        included: true,
      },
      {
        id: "qi_p4",
        category: "diagnostic",
        description: "Diagnostic fee — waived",
        amount: 0,
        included: true,
      },
      {
        id: "qi_p5",
        category: "tax",
        description: "Sales tax (7.25%)",
        amount: 48.69,
        included: true,
      },
    ],
    subtotal: 568,
    tax: 48.69,
    total: 616.69,
    currency: "USD",
    warrantyText: "12 months / 12,000 miles",
    warrantyDays: 365,
    earliestDate: "2026-07-20",
    validUntil: "2026-08-01",
    completeness: 1.0,
    conditions: [],
    confirmedInCall: true,
    warnings: [],
    createdAt: now,
  },
  {
    id: "q_queen",
    callId: "call_queen",
    shopId: "shop_queencity",
    status: "complete",
    items: [
      {
        id: "qi_q1",
        category: "parts",
        description: "Premium aftermarket pads + rotors, front",
        amount: 305,
        included: true,
        partsGrade: "premium_aftermarket",
      },
      {
        id: "qi_q2",
        category: "labor",
        description: "Front brake service labor",
        amount: 260,
        included: true,
      },
      {
        id: "qi_q3",
        category: "shop_supply",
        description: "Shop supply fee",
        amount: 35,
        included: true,
      },
      { id: "qi_q4", category: "disposal", description: "Disposal fee", amount: 5, included: true },
      {
        id: "qi_q5",
        category: "tax",
        description: "Sales tax (7.25%)",
        amount: 40,
        included: true,
      },
    ],
    subtotal: 605,
    tax: 40,
    total: 645,
    currency: "USD",
    warrantyText: "6 months",
    warrantyDays: 180,
    earliestDate: "2026-07-22",
    validUntil: "2026-07-24",
    completeness: 0.85,
    conditions: ["Visual inspection required before commitment"],
    confirmedInCall: true,
    warnings: ["initial_range_only"],
    createdAt: now,
  },
];

// Revised negotiated quote for Precision
export const seedRevisedQuote: Quote = {
  ...seedQuotes[1],
  id: "q_precision_revised",
  items: [
    seedQuotes[1].items[0],
    {
      ...seedQuotes[1].items[1],
      amount: 225,
      disclosureNote: "Reduced by $3 after verified competing-quote leverage",
    },
    {
      id: "qi_p3b",
      category: "shop_supply",
      description: "Shop supplies — waived after leverage",
      amount: 0,
      included: true,
      disclosureNote: "$28 fee waived after verified competing-quote leverage",
    },
    seedQuotes[1].items[3],
    {
      id: "qi_p5b",
      category: "tax",
      description: "Revised sales tax",
      amount: 48,
      included: true,
    },
  ],
  subtotal: 537,
  tax: 48,
  total: 585,
  warnings: ["revised_after_negotiation"],
};

export const seedNegotiation: Negotiation = {
  id: "neg_1",
  campaignId: DEMO_CAMPAIGN_ID,
  shopId: "shop_precision",
  originalQuoteId: "q_precision",
  leverageQuoteId: "q_budget",
  revisedQuoteId: undefined,
  asks: ["beat_or_match", "waive_shop_supply"],
  approvedByUser: false,
  outcome: "pending",
  createdAt: now,
};

export const seedEvidence: EvidenceSpan[] = [
  {
    id: "ev_b_all",
    callId: "call_budget",
    fieldName: "all_in_total",
    turnIndex: 9,
    speaker: "shop",
    timeSeconds: 55,
    transcriptText: "The final all-in total is $574.",
  },
  {
    id: "ev_b_fee",
    callId: "call_budget",
    fieldName: "shop_supply_fee",
    turnIndex: 3,
    speaker: "shop",
    timeSeconds: 24,
    transcriptText: "Shop fee's $45 on top, tax is separate",
  },
  {
    id: "ev_b_war",
    callId: "call_budget",
    fieldName: "warranty",
    turnIndex: 5,
    speaker: "shop",
    timeSeconds: 37,
    transcriptText: "Warranty is 90 days parts and labor",
  },
  {
    id: "ev_p_all",
    callId: "call_precision",
    fieldName: "all_in_total",
    turnIndex: 1,
    speaker: "shop",
    timeSeconds: 10,
    transcriptText: "All-in $616.69",
  },
  {
    id: "ev_p_war",
    callId: "call_precision",
    fieldName: "warranty",
    turnIndex: 1,
    speaker: "shop",
    timeSeconds: 10,
    transcriptText: "Warranty 12 months or 12,000 miles",
  },
  {
    id: "ev_p_diag",
    callId: "call_precision",
    fieldName: "diagnostic_fee",
    turnIndex: 3,
    speaker: "shop",
    timeSeconds: 25,
    transcriptText: "Waived — repair is already diagnosed",
  },
  {
    id: "ev_q_rng",
    callId: "call_queen",
    fieldName: "all_in_total",
    turnIndex: 1,
    speaker: "shop",
    timeSeconds: 8,
    transcriptText: "Somewhere between six-twenty and seven-twenty",
  },
  {
    id: "ev_q_cond",
    callId: "call_queen",
    fieldName: "conditions",
    turnIndex: 3,
    speaker: "shop",
    timeSeconds: 20,
    transcriptText: "Visual inspection required before we commit",
  },
];

export const seedAudit: AuditEvent[] = [
  {
    id: "ae_1",
    sessionId: DEMO_SESSION_ID,
    eventType: "document_uploaded",
    message: "Sample dealer estimate uploaded",
    createdAt: now,
  },
  {
    id: "ae_2",
    sessionId: DEMO_SESSION_ID,
    eventType: "extraction_completed",
    message: "Extracted 9 fields from estimate",
    createdAt: now,
  },
];
