/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as DemoArenaRouteImport } from './routes/demo.arena'
import { Route as ApiRequestsRouteImport } from './routes/api.requests'
import { Route as ApiNegotiationsRouteImport } from './routes/api.negotiations'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiCapabilitiesRouteImport } from './routes/api.capabilities'
import { Route as ApiCampaignsRouteImport } from './routes/api.campaigns'
import { Route as CampaignsIdIndexRouteImport } from './routes/campaigns.$id.index'
import { Route as RequestsIdSpecRouteImport } from './routes/requests.$id.spec'
import { Route as RequestsIdShopsRouteImport } from './routes/requests.$id.shops'
import { Route as RequestsIdIntakeRouteImport } from './routes/requests.$id.intake'
import { Route as RequestsIdExtractionRouteImport } from './routes/requests.$id.extraction'
import { Route as CampaignsIdReportRouteImport } from './routes/campaigns.$id.report'
import { Route as CampaignsIdNegotiateRouteImport } from './routes/campaigns.$id.negotiate'
import { Route as CampaignsIdCompareRouteImport } from './routes/campaigns.$id.compare'
import { Route as ApiWebhooksElevenlabsRouteImport } from './routes/api.webhooks.elevenlabs'
import { Route as ApiRequestsIdRouteImport } from './routes/api.requests.$id'
import { Route as ApiCampaignsIdRouteImport } from './routes/api.campaigns.$id'
import { Route as ApiRequestsIdVoiceTokenRouteImport } from './routes/api.requests.$id.voice-token'
import { Route as ApiRequestsIdShopsRouteImport } from './routes/api.requests.$id.shops'
import { Route as ApiRequestsIdDiscoverRouteImport } from './routes/api.requests.$id.discover'
import { Route as ApiRequestsIdActionsRouteImport } from './routes/api.requests.$id.actions'
import { Route as ApiCallsIdAudioRouteImport } from './routes/api.calls.$id.audio'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoArenaRoute = DemoArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => DemoRoute,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNegotiationsRoute = ApiNegotiationsRouteImport.update({
  id: '/api/negotiations',
  path: '/api/negotiations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapabilitiesRoute = ApiCapabilitiesRouteImport.update({
  id: '/api/capabilities',
  path: '/api/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdIndexRoute = CampaignsIdIndexRouteImport.update({
  id: '/campaigns/$id/',
  path: '/campaigns/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdSpecRoute = RequestsIdSpecRouteImport.update({
  id: '/requests/$id/spec',
  path: '/requests/$id/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdShopsRoute = RequestsIdShopsRouteImport.update({
  id: '/requests/$id/shops',
  path: '/requests/$id/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdIntakeRoute = RequestsIdIntakeRouteImport.update({
  id: '/requests/$id/intake',
  path: '/requests/$id/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdExtractionRoute = RequestsIdExtractionRouteImport.update({
  id: '/requests/$id/extraction',
  path: '/requests/$id/extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdReportRoute = CampaignsIdReportRouteImport.update({
  id: '/campaigns/$id/report',
  path: '/campaigns/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdNegotiateRoute = CampaignsIdNegotiateRouteImport.update({
  id: '/campaigns/$id/negotiate',
  path: '/campaigns/$id/negotiate',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdCompareRoute = CampaignsIdCompareRouteImport.update({
  id: '/campaigns/$id/compare',
  path: '/campaigns/$id/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksElevenlabsRoute = ApiWebhooksElevenlabsRouteImport.update({
  id: '/api/webhooks/elevenlabs',
  path: '/api/webhooks/elevenlabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsIdRoute = ApiRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRequestsRoute,
} as any)
const ApiCampaignsIdRoute = ApiCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCampaignsRoute,
} as any)
const ApiRequestsIdVoiceTokenRoute = ApiRequestsIdVoiceTokenRouteImport.update({
  id: '/voice-token',
  path: '/voice-token',
  getParentRoute: () => ApiRequestsIdRoute,
} as any)
const ApiRequestsIdShopsRoute = ApiRequestsIdShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => ApiRequestsIdRoute,
} as any)
const ApiRequestsIdDiscoverRoute = ApiRequestsIdDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => ApiRequestsIdRoute,
} as any)
const ApiRequestsIdActionsRoute = ApiRequestsIdActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ApiRequestsIdRoute,
} as any)
const ApiCallsIdAudioRoute = ApiCallsIdAudioRouteImport.update({
  id: '/api/calls/$id/audio',
  path: '/api/calls/$id/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/history': typeof HistoryRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/capabilities': typeof ApiCapabilitiesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/negotiations': typeof ApiNegotiationsRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/demo/arena': typeof DemoArenaRoute
  '/requests/new': typeof RequestsNewRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRoute
  '/api/requests/$id': typeof ApiRequestsIdRouteWithChildren
  '/api/webhooks/elevenlabs': typeof ApiWebhooksElevenlabsRoute
  '/campaigns/$id/compare': typeof CampaignsIdCompareRoute
  '/campaigns/$id/negotiate': typeof CampaignsIdNegotiateRoute
  '/campaigns/$id/report': typeof CampaignsIdReportRoute
  '/requests/$id/extraction': typeof RequestsIdExtractionRoute
  '/requests/$id/intake': typeof RequestsIdIntakeRoute
  '/requests/$id/shops': typeof RequestsIdShopsRoute
  '/requests/$id/spec': typeof RequestsIdSpecRoute
  '/campaigns/$id/': typeof CampaignsIdIndexRoute
  '/api/calls/$id/audio': typeof ApiCallsIdAudioRoute
  '/api/requests/$id/actions': typeof ApiRequestsIdActionsRoute
  '/api/requests/$id/discover': typeof ApiRequestsIdDiscoverRoute
  '/api/requests/$id/shops': typeof ApiRequestsIdShopsRoute
  '/api/requests/$id/voice-token': typeof ApiRequestsIdVoiceTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/history': typeof HistoryRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/capabilities': typeof ApiCapabilitiesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/negotiations': typeof ApiNegotiationsRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/demo/arena': typeof DemoArenaRoute
  '/requests/new': typeof RequestsNewRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRoute
  '/api/requests/$id': typeof ApiRequestsIdRouteWithChildren
  '/api/webhooks/elevenlabs': typeof ApiWebhooksElevenlabsRoute
  '/campaigns/$id/compare': typeof CampaignsIdCompareRoute
  '/campaigns/$id/negotiate': typeof CampaignsIdNegotiateRoute
  '/campaigns/$id/report': typeof CampaignsIdReportRoute
  '/requests/$id/extraction': typeof RequestsIdExtractionRoute
  '/requests/$id/intake': typeof RequestsIdIntakeRoute
  '/requests/$id/shops': typeof RequestsIdShopsRoute
  '/requests/$id/spec': typeof RequestsIdSpecRoute
  '/campaigns/$id': typeof CampaignsIdIndexRoute
  '/api/calls/$id/audio': typeof ApiCallsIdAudioRoute
  '/api/requests/$id/actions': typeof ApiRequestsIdActionsRoute
  '/api/requests/$id/discover': typeof ApiRequestsIdDiscoverRoute
  '/api/requests/$id/shops': typeof ApiRequestsIdShopsRoute
  '/api/requests/$id/voice-token': typeof ApiRequestsIdVoiceTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/history': typeof HistoryRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/capabilities': typeof ApiCapabilitiesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/negotiations': typeof ApiNegotiationsRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/demo/arena': typeof DemoArenaRoute
  '/requests/new': typeof RequestsNewRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRoute
  '/api/requests/$id': typeof ApiRequestsIdRouteWithChildren
  '/api/webhooks/elevenlabs': typeof ApiWebhooksElevenlabsRoute
  '/campaigns/$id/compare': typeof CampaignsIdCompareRoute
  '/campaigns/$id/negotiate': typeof CampaignsIdNegotiateRoute
  '/campaigns/$id/report': typeof CampaignsIdReportRoute
  '/requests/$id/extraction': typeof RequestsIdExtractionRoute
  '/requests/$id/intake': typeof RequestsIdIntakeRoute
  '/requests/$id/shops': typeof RequestsIdShopsRoute
  '/requests/$id/spec': typeof RequestsIdSpecRoute
  '/campaigns/$id/': typeof CampaignsIdIndexRoute
  '/api/calls/$id/audio': typeof ApiCallsIdAudioRoute
  '/api/requests/$id/actions': typeof ApiRequestsIdActionsRoute
  '/api/requests/$id/discover': typeof ApiRequestsIdDiscoverRoute
  '/api/requests/$id/shops': typeof ApiRequestsIdShopsRoute
  '/api/requests/$id/voice-token': typeof ApiRequestsIdVoiceTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/history'
    | '/api/campaigns'
    | '/api/capabilities'
    | '/api/health'
    | '/api/negotiations'
    | '/api/requests'
    | '/demo/arena'
    | '/requests/new'
    | '/api/campaigns/$id'
    | '/api/requests/$id'
    | '/api/webhooks/elevenlabs'
    | '/campaigns/$id/compare'
    | '/campaigns/$id/negotiate'
    | '/campaigns/$id/report'
    | '/requests/$id/extraction'
    | '/requests/$id/intake'
    | '/requests/$id/shops'
    | '/requests/$id/spec'
    | '/campaigns/$id/'
    | '/api/calls/$id/audio'
    | '/api/requests/$id/actions'
    | '/api/requests/$id/discover'
    | '/api/requests/$id/shops'
    | '/api/requests/$id/voice-token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/history'
    | '/api/campaigns'
    | '/api/capabilities'
    | '/api/health'
    | '/api/negotiations'
    | '/api/requests'
    | '/demo/arena'
    | '/requests/new'
    | '/api/campaigns/$id'
    | '/api/requests/$id'
    | '/api/webhooks/elevenlabs'
    | '/campaigns/$id/compare'
    | '/campaigns/$id/negotiate'
    | '/campaigns/$id/report'
    | '/requests/$id/extraction'
    | '/requests/$id/intake'
    | '/requests/$id/shops'
    | '/requests/$id/spec'
    | '/campaigns/$id'
    | '/api/calls/$id/audio'
    | '/api/requests/$id/actions'
    | '/api/requests/$id/discover'
    | '/api/requests/$id/shops'
    | '/api/requests/$id/voice-token'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/history'
    | '/api/campaigns'
    | '/api/capabilities'
    | '/api/health'
    | '/api/negotiations'
    | '/api/requests'
    | '/demo/arena'
    | '/requests/new'
    | '/api/campaigns/$id'
    | '/api/requests/$id'
    | '/api/webhooks/elevenlabs'
    | '/campaigns/$id/compare'
    | '/campaigns/$id/negotiate'
    | '/campaigns/$id/report'
    | '/requests/$id/extraction'
    | '/requests/$id/intake'
    | '/requests/$id/shops'
    | '/requests/$id/spec'
    | '/campaigns/$id/'
    | '/api/calls/$id/audio'
    | '/api/requests/$id/actions'
    | '/api/requests/$id/discover'
    | '/api/requests/$id/shops'
    | '/api/requests/$id/voice-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  ApiCampaignsRoute: typeof ApiCampaignsRouteWithChildren
  ApiCapabilitiesRoute: typeof ApiCapabilitiesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNegotiationsRoute: typeof ApiNegotiationsRoute
  ApiRequestsRoute: typeof ApiRequestsRouteWithChildren
  RequestsNewRoute: typeof RequestsNewRoute
  ApiWebhooksElevenlabsRoute: typeof ApiWebhooksElevenlabsRoute
  CampaignsIdCompareRoute: typeof CampaignsIdCompareRoute
  CampaignsIdNegotiateRoute: typeof CampaignsIdNegotiateRoute
  CampaignsIdReportRoute: typeof CampaignsIdReportRoute
  RequestsIdExtractionRoute: typeof RequestsIdExtractionRoute
  RequestsIdIntakeRoute: typeof RequestsIdIntakeRoute
  RequestsIdShopsRoute: typeof RequestsIdShopsRoute
  RequestsIdSpecRoute: typeof RequestsIdSpecRoute
  CampaignsIdIndexRoute: typeof CampaignsIdIndexRoute
  ApiCallsIdAudioRoute: typeof ApiCallsIdAudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/arena': {
      id: '/demo/arena'
      path: '/arena'
      fullPath: '/demo/arena'
      preLoaderRoute: typeof DemoArenaRouteImport
      parentRoute: typeof DemoRoute
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/negotiations': {
      id: '/api/negotiations'
      path: '/api/negotiations'
      fullPath: '/api/negotiations'
      preLoaderRoute: typeof ApiNegotiationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capabilities': {
      id: '/api/capabilities'
      path: '/api/capabilities'
      fullPath: '/api/capabilities'
      preLoaderRoute: typeof ApiCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id/': {
      id: '/campaigns/$id/'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id/'
      preLoaderRoute: typeof CampaignsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/spec': {
      id: '/requests/$id/spec'
      path: '/requests/$id/spec'
      fullPath: '/requests/$id/spec'
      preLoaderRoute: typeof RequestsIdSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/shops': {
      id: '/requests/$id/shops'
      path: '/requests/$id/shops'
      fullPath: '/requests/$id/shops'
      preLoaderRoute: typeof RequestsIdShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/intake': {
      id: '/requests/$id/intake'
      path: '/requests/$id/intake'
      fullPath: '/requests/$id/intake'
      preLoaderRoute: typeof RequestsIdIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/extraction': {
      id: '/requests/$id/extraction'
      path: '/requests/$id/extraction'
      fullPath: '/requests/$id/extraction'
      preLoaderRoute: typeof RequestsIdExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id/report': {
      id: '/campaigns/$id/report'
      path: '/campaigns/$id/report'
      fullPath: '/campaigns/$id/report'
      preLoaderRoute: typeof CampaignsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id/negotiate': {
      id: '/campaigns/$id/negotiate'
      path: '/campaigns/$id/negotiate'
      fullPath: '/campaigns/$id/negotiate'
      preLoaderRoute: typeof CampaignsIdNegotiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id/compare': {
      id: '/campaigns/$id/compare'
      path: '/campaigns/$id/compare'
      fullPath: '/campaigns/$id/compare'
      preLoaderRoute: typeof CampaignsIdCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/elevenlabs': {
      id: '/api/webhooks/elevenlabs'
      path: '/api/webhooks/elevenlabs'
      fullPath: '/api/webhooks/elevenlabs'
      preLoaderRoute: typeof ApiWebhooksElevenlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests/$id': {
      id: '/api/requests/$id'
      path: '/$id'
      fullPath: '/api/requests/$id'
      preLoaderRoute: typeof ApiRequestsIdRouteImport
      parentRoute: typeof ApiRequestsRoute
    }
    '/api/campaigns/$id': {
      id: '/api/campaigns/$id'
      path: '/$id'
      fullPath: '/api/campaigns/$id'
      preLoaderRoute: typeof ApiCampaignsIdRouteImport
      parentRoute: typeof ApiCampaignsRoute
    }
    '/api/requests/$id/voice-token': {
      id: '/api/requests/$id/voice-token'
      path: '/voice-token'
      fullPath: '/api/requests/$id/voice-token'
      preLoaderRoute: typeof ApiRequestsIdVoiceTokenRouteImport
      parentRoute: typeof ApiRequestsIdRoute
    }
    '/api/requests/$id/shops': {
      id: '/api/requests/$id/shops'
      path: '/shops'
      fullPath: '/api/requests/$id/shops'
      preLoaderRoute: typeof ApiRequestsIdShopsRouteImport
      parentRoute: typeof ApiRequestsIdRoute
    }
    '/api/requests/$id/discover': {
      id: '/api/requests/$id/discover'
      path: '/discover'
      fullPath: '/api/requests/$id/discover'
      preLoaderRoute: typeof ApiRequestsIdDiscoverRouteImport
      parentRoute: typeof ApiRequestsIdRoute
    }
    '/api/requests/$id/actions': {
      id: '/api/requests/$id/actions'
      path: '/actions'
      fullPath: '/api/requests/$id/actions'
      preLoaderRoute: typeof ApiRequestsIdActionsRouteImport
      parentRoute: typeof ApiRequestsIdRoute
    }
    '/api/calls/$id/audio': {
      id: '/api/calls/$id/audio'
      path: '/api/calls/$id/audio'
      fullPath: '/api/calls/$id/audio'
      preLoaderRoute: typeof ApiCallsIdAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DemoRouteChildren {
  DemoArenaRoute: typeof DemoArenaRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoArenaRoute: DemoArenaRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface ApiCampaignsRouteChildren {
  ApiCampaignsIdRoute: typeof ApiCampaignsIdRoute
}

const ApiCampaignsRouteChildren: ApiCampaignsRouteChildren = {
  ApiCampaignsIdRoute: ApiCampaignsIdRoute,
}

const ApiCampaignsRouteWithChildren = ApiCampaignsRoute._addFileChildren(
  ApiCampaignsRouteChildren,
)

interface ApiRequestsIdRouteChildren {
  ApiRequestsIdActionsRoute: typeof ApiRequestsIdActionsRoute
  ApiRequestsIdDiscoverRoute: typeof ApiRequestsIdDiscoverRoute
  ApiRequestsIdShopsRoute: typeof ApiRequestsIdShopsRoute
  ApiRequestsIdVoiceTokenRoute: typeof ApiRequestsIdVoiceTokenRoute
}

const ApiRequestsIdRouteChildren: ApiRequestsIdRouteChildren = {
  ApiRequestsIdActionsRoute: ApiRequestsIdActionsRoute,
  ApiRequestsIdDiscoverRoute: ApiRequestsIdDiscoverRoute,
  ApiRequestsIdShopsRoute: ApiRequestsIdShopsRoute,
  ApiRequestsIdVoiceTokenRoute: ApiRequestsIdVoiceTokenRoute,
}

const ApiRequestsIdRouteWithChildren = ApiRequestsIdRoute._addFileChildren(
  ApiRequestsIdRouteChildren,
)

interface ApiRequestsRouteChildren {
  ApiRequestsIdRoute: typeof ApiRequestsIdRouteWithChildren
}

const ApiRequestsRouteChildren: ApiRequestsRouteChildren = {
  ApiRequestsIdRoute: ApiRequestsIdRouteWithChildren,
}

const ApiRequestsRouteWithChildren = ApiRequestsRoute._addFileChildren(
  ApiRequestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  HistoryRoute: HistoryRoute,
  ApiCampaignsRoute: ApiCampaignsRouteWithChildren,
  ApiCapabilitiesRoute: ApiCapabilitiesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNegotiationsRoute: ApiNegotiationsRoute,
  ApiRequestsRoute: ApiRequestsRouteWithChildren,
  RequestsNewRoute: RequestsNewRoute,
  ApiWebhooksElevenlabsRoute: ApiWebhooksElevenlabsRoute,
  CampaignsIdCompareRoute: CampaignsIdCompareRoute,
  CampaignsIdNegotiateRoute: CampaignsIdNegotiateRoute,
  CampaignsIdReportRoute: CampaignsIdReportRoute,
  RequestsIdExtractionRoute: RequestsIdExtractionRoute,
  RequestsIdIntakeRoute: RequestsIdIntakeRoute,
  RequestsIdShopsRoute: RequestsIdShopsRoute,
  RequestsIdSpecRoute: RequestsIdSpecRoute,
  CampaignsIdIndexRoute: CampaignsIdIndexRoute,
  ApiCallsIdAudioRoute: ApiCallsIdAudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
